config/routes.rb
Rails.application.routes.draw do
  resources :cursos
  resources :inscripciones
  root 'welcome#index'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/curso.rb
class Curso < ApplicationRecord
end

app/models/inscripcione.rb
class Inscripcione < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cursos_controller.rb
class CursosController < ApplicationController
  before_action :set_curso, only: [:show, :edit, :update, :destroy]

  # GET /cursos
  # GET /cursos.json
  def index
    @cursos = Curso.all
  end

  # GET /cursos/1
  # GET /cursos/1.json
  def show
  end

  # GET /cursos/new
  def new
    @curso = Curso.new
  end

  # GET /cursos/1/edit
  def edit
  end

  # POST /cursos
  # POST /cursos.json
  def create
    @curso = Curso.new(curso_params)

    respond_to do |format|
      if @curso.save
        format.html { redirect_to @curso, notice: 'Curso was successfully created.' }
        format.json { render :show, status: :created, location: @curso }
      else
        format.html { render :new }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cursos/1
  # PATCH/PUT /cursos/1.json
  def update
    respond_to do |format|
      if @curso.update(curso_params)
        format.html { redirect_to @curso, notice: 'Curso was successfully updated.' }
        format.json { render :show, status: :ok, location: @curso }
      else
        format.html { render :edit }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cursos/1
  # DELETE /cursos/1.json
  def destroy
    @curso.destroy
    respond_to do |format|
      format.html { redirect_to cursos_url, notice: 'Curso was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curso
      @curso = Curso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def curso_params
      params.require(:curso).permit(:id_materia, :nombre, :num_creditos, :cupo_max, :cupo_min)
    end
end

app/controllers/inscripciones_controller.rb
class InscripcionesController < ApplicationController
  before_action :set_inscripcione, only: [:show, :edit, :update, :destroy]

  # GET /inscripciones
  # GET /inscripciones.json
  def index
    @inscripciones = Inscripcione.all
  end

  # GET /inscripciones/1
  # GET /inscripciones/1.json
  def show
  end

  # GET /inscripciones/new
  def new
    @inscripcione = Inscripcione.new
  end

  # GET /inscripciones/1/edit
  def edit
  end

  # POST /inscripciones
  # POST /inscripciones.json
  def create
    @inscripcione = Inscripcione.new(inscripcione_params)

    respond_to do |format|
      if @inscripcione.save
        format.html { redirect_to @inscripcione, notice: 'Inscripcione was successfully created.' }
        format.json { render :show, status: :created, location: @inscripcione }
      else
        format.html { render :new }
        format.json { render json: @inscripcione.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inscripciones/1
  # PATCH/PUT /inscripciones/1.json
  def update
    respond_to do |format|
      if @inscripcione.update(inscripcione_params)
        format.html { redirect_to @inscripcione, notice: 'Inscripcione was successfully updated.' }
        format.json { render :show, status: :ok, location: @inscripcione }
      else
        format.html { render :edit }
        format.json { render json: @inscripcione.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inscripciones/1
  # DELETE /inscripciones/1.json
  def destroy
    @inscripcione.destroy
    respond_to do |format|
      format.html { redirect_to inscripciones_url, notice: 'Inscripcione was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inscripcione
      @inscripcione = Inscripcione.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inscripcione_params
      params.require(:inscripcione).permit(:id_inscripcion, :documento, :curso, :estrato, :valor_credito)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :bio, :subject, :nacionality)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/inscripciones_helper.rb
module InscripcionesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cursos/_form.html.erb
<%= form_for(curso) do |f| %>
  <% if curso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(curso.errors.count, "error") %> prohibited this curso from being saved:</h2>

      <ul>
      <% curso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_materia %>
    <%= f.text_field :id_materia %>
  </div>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :num_creditos %>
    <%= f.number_field :num_creditos %>
  </div>

  <div class="field">
    <%= f.label :cupo_max %>
    <%= f.number_field :cupo_max %>
  </div>

  <div class="field">
    <%= f.label :cupo_min %>
    <%= f.number_field :cupo_min %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cursos/edit.html.erb
<h1>Editing Curso</h1>

<%= render 'form', curso: @curso %>

<%= link_to 'Show', @curso %> |
<%= link_to 'Back', cursos_path %>

app/views/cursos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cursos</h1>

<table>
  <thead>
    <tr>
      <th>Id materia</th>
      <th>Nombre</th>
      <th>Num creditos</th>
      <th>Cupo max</th>
      <th>Cupo min</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cursos.each do |curso| %>
      <tr>
        <td><%= curso.id_materia %></td>
        <td><%= curso.nombre %></td>
        <td><%= curso.num_creditos %></td>
        <td><%= curso.cupo_max %></td>
        <td><%= curso.cupo_min %></td>
        <td><%= link_to 'Show', curso %></td>
        <td><%= link_to 'Edit', edit_curso_path(curso) %></td>
        <td><%= link_to 'Destroy', curso, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo curso', new_curso_path %>
<%= link_to 'Página principal', root_path %>

app/views/cursos/new.html.erb
<h1>New Curso</h1>

<%= render 'form', curso: @curso %>

<%= link_to 'Back', cursos_path %>

app/views/cursos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id materia:</strong>
  <%= @curso.id_materia %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @curso.nombre %>
</p>

<p>
  <strong>Num creditos:</strong>
  <%= @curso.num_creditos %>
</p>

<p>
  <strong>Cupo max:</strong>
  <%= @curso.cupo_max %>
</p>

<p>
  <strong>Cupo min:</strong>
  <%= @curso.cupo_min %>
</p>

<%= link_to 'Edit', edit_curso_path(@curso) %> |
<%= link_to 'Back', cursos_path %>

app/views/inscripciones/_form.html.erb
<%= form_for(inscripcione) do |f| %>
  <% if inscripcione.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inscripcione.errors.count, "error") %> prohibited this inscripcione from being saved:</h2>

      <ul>
      <% inscripcione.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_inscripcion %>
    <%= f.text_field :id_inscripcion %>
  </div>

  <div class="field">
    <%= f.label :documento %>
    <%= f.text_field :documento %>
  </div>

  <div class="field">
    <%= f.label :curso %>
    <%= f.text_field :curso %>
  </div>

  <div class="field">
    <%= f.label :estrato %>
    <%= f.number_field :estrato %>
  </div>

  <div class="field">
    <%= f.label :valor_credito %>
    <%= f.number_field :valor_credito %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inscripciones/edit.html.erb
<h1>Editing Inscripcione</h1>

<%= render 'form', inscripcione: @inscripcione %>

<%= link_to 'Show', @inscripcione %> |
<%= link_to 'Back', inscripciones_path %>

app/views/inscripciones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inscripciones</h1>

<table>
  <thead>
    <tr>
      <th>Id inscripcion</th>
      <th>Documento</th>
      <th>Curso</th>
      <th>Estrato</th>
      <th>Valor credito</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inscripciones.each do |inscripcione| %>
      <tr>
        <td><%= inscripcione.id_inscripcion %></td>
        <td><%= inscripcione.documento %></td>
        <td><%= inscripcione.curso %></td>
        <td><%= inscripcione.estrato %></td>
        <td><%= inscripcione.valor_credito %></td>
        <td><%= link_to 'Show', inscripcione %></td>
        <td><%= link_to 'Edit', edit_inscripcione_path(inscripcione) %></td>
        <td><%= link_to 'Destroy', inscripcione, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva inscripción', new_inscripcione_path %>
<%= link_to 'Página principla', root_path %>

app/views/inscripciones/new.html.erb
<h1>New Inscripcione</h1>

<%= render 'form', inscripcione: @inscripcione %>

<%= link_to 'Back', inscripciones_path %>

app/views/inscripciones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id inscripcion:</strong>
  <%= @inscripcione.id_inscripcion %>
</p>

<p>
  <strong>Documento:</strong>
  <%= @inscripcione.documento %>
</p>

<p>
  <strong>Curso:</strong>
  <%= @inscripcione.curso %>
</p>

<p>
  <strong>Estrato:</strong>
  <%= @inscripcione.estrato %>
</p>

<p>
  <strong>Valor credito:</strong>
  <%= @inscripcione.valor_credito %>
</p>

<%= link_to 'Edit', edit_inscripcione_path(@inscripcione) %> |
<%= link_to 'Back', inscripciones_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Parcial</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :bio %>
    <%= f.text_field :bio %>
  </div>

  <div class="field">
    <%= f.label :subject %>
    <%= f.text_field :subject %>
  </div>

  <div class="field">
    <%= f.label :nacionality %>
    <%= f.text_field :nacionality %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Subject</th>
      <th>Nacionality</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.bio %></td>
        <td><%= user.subject %></td>
        <td><%= user.nacionality %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @user.subject %>
</p>

<p>
  <strong>Nacionality:</strong>
  <%= @user.nacionality %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Parcial final programación distribuida y paralela</h1>
<h2>Por:Angel Manuel Góez Giraldo | 1036658046</h2>

<%= link_to 'Nuevo curso', cursos_path %>
<%= link_to 'Nueva inscripción', inscripciones_path %>